force-app/main/default/objects/Storefront_Collection__c/Storefront_Collection__c.object-meta.xml
<CustomObject>
    <label>Storefront Collection</label>
    <nameField>
        <label>Storefront Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Storefront Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Storefront_Collection__c/fields/Navigation_Icon__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Icon__c</fullName>
    <description>SLDS Icon for the Navigation Menu</description>
    <label>Navigation Icon</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Navigation_Name__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Name__c</fullName>
    <description>Name of the storefront collection that appears on the vertical navigation</description>
    <label>Navigation Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Primary_Button_Icon__c.field-meta.xml
<CustomField>
    <fullName>Primary_Button_Icon__c</fullName>
    <description>SLDS icon name for primary button</description>
    <label>Primary Button Icon</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Primary_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Primary_Button_Label__c</fullName>
    <label>Primary Button Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Primary_Button_Link__c.field-meta.xml
<CustomField>
    <fullName>Primary_Button_Link__c</fullName>
    <label>Primary Button Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Secondary_Button_Icon__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Button_Icon__c</fullName>
    <label>Secondary Button Icon</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Secondary_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Button_Label__c</fullName>
    <label>Secondary Button Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Collection__c/fields/Secondary_Button_Link__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Button_Link__c</fullName>
    <label>Secondary Button Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storefront_Item__c/Storefront_Item__c.object-meta.xml
<CustomObject>
    <description>List of items that make up the Storefront</description>
    <label>Storefront Item</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Storefront Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storefront Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Storefront_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the storefront item</description>
    <label>Description</label>
    <length>160</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Item__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>SLDS icon name of the storefront item</description>
    <label>Icon Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Item__c/fields/In_App_Guidance_Link__c.field-meta.xml
<CustomField>
    <fullName>In_App_Guidance_Link__c</fullName>
    <description>Link to the In-App Guidance Walkthrough</description>
    <label>In App Guidance Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storefront_Item__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label of the Storefront Item</description>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Item__c/fields/Storefront_Collection__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Collection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Storefront Collection</label>
    <referenceTo>Storefront_Collection__c</referenceTo>
    <relationshipLabel>Storefront Items</relationshipLabel>
    <relationshipName>Storefront_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Setup__c/Storefront_Item_Setup__c.object-meta.xml
<CustomObject>
    <label>Storefront Item Setup</label>
    <nameField>
        <displayFormat>SISN-{0000}</displayFormat>
        <label>Storefront Item Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storefront Item Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Storefront_Item_Setup__c/fields/Storefront_Item__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Storefront Item</label>
    <referenceTo>Storefront_Item__c</referenceTo>
    <relationshipLabel>Storefront Item Setups</relationshipLabel>
    <relationshipName>Storefront_Item_Setups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Setup__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/Storefront_Item_Step__c.object-meta.xml
<CustomObject>
    <label>Storefront Item Step</label>
    <nameField>
        <displayFormat>SIS - {0000}</displayFormat>
        <label>Storefront Item Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Storefront Item Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Storefront_Item_Step__c/fields/Button_Icon__c.field-meta.xml
<CustomField>
    <fullName>Button_Icon__c</fullName>
    <label>Button Icon</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/Button_Type__c.field-meta.xml
<CustomField>
    <fullName>Button_Type__c</fullName>
    <label>Button Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>standard</fullName>
            </value>
            <value>
                <fullName>icon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/Button_Variant__c.field-meta.xml
<CustomField>
    <fullName>Button_Variant__c</fullName>
    <label>Button Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>base</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>brand-outline</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>destructive-text</fullName>
            </value>
            <value>
                <fullName>inverse</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>ISPICKVAL(Status__c, &quot;active&quot;)</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <formula>ISPICKVAL(Status__c, &quot;completed&quot;)</formula>
    <label>IsCompleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/IsMarker__c.field-meta.xml
<CustomField>
    <fullName>IsMarker__c</fullName>
    <formula>ISPICKVAL(Status__c, &quot;marker&quot;)</formula>
    <label>IsMarker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>completed</fullName>
            </value>
            <value>
                <fullName>marker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Storefront_Item_Step__c/fields/Storefront_Item_Setup__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Item_Setup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Storefront Item Setup</label>
    <referenceTo>Storefront_Item_Setup__c</referenceTo>
    <relationshipLabel>Storefront Item Steps</relationshipLabel>
    <relationshipName>Storefront_Item_Steps</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Mat_Item__c/Welcome_Mat_Item__c.object-meta.xml
<CustomObject>
    <label>Welcome Mat Item</label>
    <nameField>
        <displayFormat>WMT-{0000}</displayFormat>
        <label>Welcome Mat Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Welcome Mat Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Mat_Item__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Welcome_Mat_Item__c/fields/Link_Type__c.field-meta.xml
<CustomField>
    <fullName>Link_Type__c</fullName>
    <label>Link Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>web</fullName>
            </value>
            <value>
                <fullName>agentforce</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketplaceController.cls
public with sharing class MarketplaceController {
    @AuraEnabled(cacheable=true)
    public static Object invokePromptAndUserModelsGenAi(String className, String methodName, String modelName, String userPrompt, String systemPrompt) {
        try { 
            String namespacedClass = className; 
            Callable callableInstance = (Callable) Type.forName(className).newInstance(); 
            Map<String, Object> payload = new Map<String, Object> { 
                'modelName' => modelName, 
                'userPrompt' => userPrompt, 
                'systemPrompt' => systemPrompt  
            }; 
            String result = (String) callableInstance.call(methodName, payload); 
            return result; 
        } catch (Exception e) { 
            throw new AuraHandledException(e.getMessage()); 
        }
    }

    @AuraEnabled(cacheable=true)
    public static Object invokeModelsGenAi(String className, String methodName, String modelName, String prompt) {
        try { 
            String namespacedClass = className; 
            Callable callableInstance = (Callable) Type.forName(className).newInstance(); 
            Map<String, Object> payload = new Map<String, Object> { 
                'modelName' => modelName, 
                'prompt' => prompt 
            }; 
            String result = (String) callableInstance.call(methodName, payload); 
            return result; 
        } catch (Exception e) { 
            throw new AuraHandledException(e.getMessage()); 
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Welcome_Mat_Item__c> getWelcomeMatItems() {
        List<Welcome_Mat_Item__c> items = new List<Welcome_Mat_Item__c>();
        try {
            items = [
                SELECT Description__c, Name, Order__c, Title__c, Link__c, Icon__c, Link_Type__c
                FROM Welcome_Mat_Item__c 
                ORDER BY Order__c ASC NULLS FIRST
                LIMIT 50
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching welcome mat items: ' + e.getMessage());
        }
        return items;
    }

    @AuraEnabled(cacheable=true)
    public static List<Storefront_Item_Setup__c> getStorefrontSetupItems(String itemName) {
        List<Storefront_Item_Setup__c> items = new List<Storefront_Item_Setup__c>();
        try {
            items = [
                SELECT Description__c, Name, Order__c, Time__c, Title__c, Storefront_Item__c, (SELECT Button_Label__c,Button_Type__c,Button_Variant__c,Description__c,Link__c,Name,Order__c,Status__c,Storefront_Item_Setup__c,IsActive__c,IsCompleted__c,IsMarker__c,Button_Icon__c FROM Storefront_Item_Steps__r ORDER BY Order__c ASC NULLS FIRST)
                FROM Storefront_Item_Setup__c 
                WHERE Storefront_Item__r.Label__c = :itemName
                ORDER BY Order__c ASC NULLS FIRST
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching storefront items: ' + e.getMessage());
        }
        return items;
    }

    @AuraEnabled(cacheable=true)
    public static List<Storefront_Collection__c> getStorefrontCollectionItems() {
        List<Storefront_Collection__c> items = new List<Storefront_Collection__c>();
        try {
            items = [
                SELECT Icon_Name__c, Name, Navigation_Icon__c, Navigation_Name__c, Order__c, Primary_Button_Icon__c, Primary_Button_Label__c, Primary_Button_Link__c, Secondary_Button_Icon__c, Secondary_Button_Label__c, Secondary_Button_Link__c
                FROM Storefront_Collection__c 
                ORDER BY Order__c ASC NULLS FIRST
                LIMIT 10
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching storefront items: ' + e.getMessage());
        }
        return items;
    }

    @AuraEnabled(cacheable=true)
    public static Account getAnyAccountRecordForMail() {
        try {
            // Query to get a single Account record
            Account accountRecord = [
                SELECT Id
                FROM Account
                LIMIT 1
            ];
            return accountRecord;
        } catch (Exception e) {
            throw new AuraHandledException('Error fetching account record: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Storefront_Item__c> getStorefrontItemsByCollection(String collectionName) {
        try {
            // Query to get Storefront_Item__c records based on the given Storefront_Collection__c Id
            List<Storefront_Item__c> storefrontItems = [
                SELECT Id, Description__c, Icon_Name__c, In_App_Guidance_Link__c, Storefront_Collection__c, Label__c
                FROM Storefront_Item__c
                WHERE Storefront_Collection__r.Name = :collectionName
                ORDER BY Name ASC
                LIMIT 20
            ];
            return storefrontItems;
        } catch (Exception e) {
            // Handle exceptions by logging the error and returning an empty list
            System.debug('Error fetching storefront items: ' + e.getMessage());
            return new List<Storefront_Item__c>();
        }
    }

}